dir: gen/mocks/{{trimPrefix "internal/" .InterfaceDirRelative}}
structname: Mock{{.InterfaceName}}
pkgname: '{{.SrcPackageName}}'
filename: '{{.InterfaceName | snakecase}}_mock.go'
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/ChargePi/chargeflow-registry/internal/grpc:
    interfaces:
      AdminService: {}
      SchemaService: {}
      ValidationService: {}
  github.com/ChargePi/chargeflow-registry/internal/schema:
    interfaces:
      Cache: {}
      Repository: {}
  github.com/ChargePi/chargeflow-registry/internal/validation:
    interfaces:
      SchemaGetter: {}
