with-expecter: true
dir: gen/mocks/{{.InterfaceDirRelative}}
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName|snakecase}}_mock.go"
packages:
  github.com/ChargePi/chargeflow-registry/internal/schema:
    interfaces:
      Repository:
      Cache:
  github.com/ChargePi/chargeflow-registry/internal/grpc:
    interfaces:
      SchemaService:
      ValidationService:
      AdminService:
  github.com/ChargePi/chargeflow-registry/internal/validation:
    interfaces:
      SchemaGetter:
