version: "3.9"
services:

  chargeflow-registry:
    environment:
      - CHARGEFLOW_REGISTRY_OBSERVABILITY_TRACING_ENABLED=true
      - CHARGEFLOW_REGISTRY_OBSERVABILITY_TRACING_ADDRESS=grafana-lgtm-stack:4317
      - CHARGEFLOW_REGISTRY_OBSERVABILITY_METRICS_ENABLED=true
      - CHARGEFLOW_REGISTRY_OBSERVABILITY_METRICS_ADDRESS=grafana-lgtm-stack:4317
      - CHARGEFLOW_REGISTRY_OBSERVABILITY_LOGGING_LEVEL=info
      - CHARGEFLOW_REGISTRY_OBSERVABILITY_LOGGING_OTELLOGGER_ADDRESS=grafana-lgtm-stack:4317

  grafana-lgtm-stack:
    image: grafana/otel-lgtm
    container_name: lgtm-stack
    hostname: lgtm-stack
    profiles:
      - observability
    environment:
      - GF_LOG_LEVEL="debug"
    volumes:
      - prometheus:/prometheus
      - loki:/data/loki
      - grafana:/var/lib/grafana

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command:
      - "-config.file=/etc/promtail/promtail.yaml"
    profiles:
      - observability
    hostname: promtail
    restart: always
    depends_on:
      - grafana-lgtm-stack
    volumes:
      - ./observability/promtail/config.yaml:/etc/promtail/promtail.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  prometheus:
  grafana:
  loki:
